version: '3.8'

volumes:
  ddon-mariadb-volume:

services:
  mariadb:
    container_name: ddon-mariadb
    image: mariadb:11
    ports:
      - "3306:3306"
    restart: no
    volumes:
      - ddon-mariadb-volume:/var/lib/mysql
      - $PWD/../../Arrowgene.Ddon.Database/Files/Database/Script/schema_mariadb.sql:/docker-entrypoint-initdb.d/schema_mariadb.sql:ro
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=mariadb
      - LANG=C.UTF_8
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 3s
      retries: 10
