version: '3.3'
volumes:
  psql_data:
    driver: local

services:
  psql:
    container_name: ddon_postgresql
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - psql_data:/var/lib/postgresql/data
      - $PWD/../../Arrowgene.Ddon.Database/Files/Database/Script/schema_postgres.sql:/docker-entrypoint-initdb.d/schema_postgres.sql:ro
      - $PWD/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256 --lc-numeric=en_US.UTF-8
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
